INSERT INTO MENU (MENU_ID, MENU_NAME, MENU_TYPE, MENU_STATE) VALUES
    (1, '기본 메뉴', 'DEFAULT', 'AVAILABLE');

INSERT INTO MENU_ITEM (MENU_ITEM_NAME, PRICE, MENU_ITEM_STATE, MENU_ID) VALUES
    ('SWEET STEAK', 10000, 'AVAILABLE', 1),
    ('SIZE UP', 15000, 'AVAILABLE', 1),
    ('FRIED RICE', 2000, 'AVAILABLE', 1);