-- 메뉴 테이블
CREATE TABLE IF NOT EXISTS MENU (
    MENU_ID INT NOT NULL AUTO_INCREMENT,
    MENU_NAME VARCHAR(50) NOT NULL,
    MENU_TYPE VARCHAR(20) NOT NULL,       -- 음식/음료/주류 등
    MENU_STATE VARCHAR(20) NOT NULL,      -- 판매중/품절/단종
    PRIMARY KEY (MENU_ID)
);

-- 메뉴 아이템 (실제 판매 단위)
CREATE TABLE IF NOT EXISTS MENU_ITEM (
    MENU_ITEM_ID BIGINT NOT NULL AUTO_INCREMENT,
    MENU_ID INT NOT NULL,
    MENU_ITEM_NAME VARCHAR(50) NOT NULL,
    PRICE INT NOT NULL,                   -- 공급가액 기준
    TAX_RATE DECIMAL(5,2) DEFAULT 10.00,  -- 세율 (%)
    MENU_ITEM_STATE VARCHAR(20) NOT NULL,
    PRIMARY KEY (MENU_ITEM_ID),
    FOREIGN KEY (MENU_ID) REFERENCES MENU(MENU_ID)
);

-- 주문 테이블
CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_NO CHAR(24) NOT NULL,
    ORDER_DATE DATETIME NOT NULL,
    ORDER_STATE VARCHAR(20) NOT NULL,     -- 완료/취소/환불 등
    SUBTOTAL INT NOT NULL,                -- 공급가액 합계
    TAX_AMOUNT INT NOT NULL,              -- 부가세 합계
    TOTAL_AMOUNT INT NOT NULL,            -- 총액 (SUBTOTAL + TAX_AMOUNT)
    WAITING_NO INT,
    PRIMARY KEY (ORDER_NO)
);

-- 주문 상세
CREATE TABLE IF NOT EXISTS ORDER_ITEM (
    ORDER_ITEM_ID BIGINT NOT NULL AUTO_INCREMENT,
    ORDER_NO CHAR(24) NOT NULL,
    MENU_ITEM_ID BIGINT NOT NULL,
    ORDER_ITEM_NAME VARCHAR(50) NOT NULL,
    PRICE INT NOT NULL,                   -- 단가 (공급가액)
    QUANTITY SMALLINT NOT NULL,
    AMOUNT INT NOT NULL,                  -- 소계 (PRICE * QUANTITY)
    PRIMARY KEY (ORDER_ITEM_ID),
    FOREIGN KEY (ORDER_NO) REFERENCES ORDERS(ORDER_NO),
    FOREIGN KEY (MENU_ITEM_ID) REFERENCES MENU_ITEM(MENU_ITEM_ID)
);

-- 결제 테이블
CREATE TABLE IF NOT EXISTS PAYMENT (
    PAYMENT_ID BIGINT NOT NULL AUTO_INCREMENT,
    ORDER_NO CHAR(24) NOT NULL,
    PAYMENT_DATE DATETIME NOT NULL,
    PAYMENT_METHOD VARCHAR(20) NOT NULL,  -- 카드/현금/간편결제
    PAYMENT_STATE VARCHAR(20) NOT NULL,   -- 승인/취소/환불
    PAID_AMOUNT INT NOT NULL,             -- 결제금액 (총액, 부가세 포함)
    CARD_FEE INT DEFAULT 0,               -- 카드 수수료
    NET_AMOUNT INT,                       -- 실제 입금액 (PAID_AMOUNT - CARD_FEE)
    PRIMARY KEY (PAYMENT_ID),
    FOREIGN KEY (ORDER_NO) REFERENCES ORDERS(ORDER_NO)
);

-- 세금 계산 스냅샷 테이블
CREATE TABLE IF NOT EXISTS TAX_CALCULATION (
    TAX_ID BIGINT NOT NULL AUTO_INCREMENT,
    ORDER_NO CHAR(24),
    PAYMENT_ID BIGINT,
    SUBTOTAL INT NOT NULL,                -- 공급가액
    TAX_AMOUNT INT NOT NULL,              -- 부가세
    TOTAL_AMOUNT INT NOT NULL,            -- 총액
    TAX_RATE DECIMAL(5,2) NOT NULL,       -- 적용 세율
    CALCULATED_AT DATETIME NOT NULL,      -- 계산 시점
    PRIMARY KEY (TAX_ID),
    FOREIGN KEY (ORDER_NO) REFERENCES ORDERS(ORDER_NO),
    FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT(PAYMENT_ID)
);

-- 세율 이력 관리 테이블
CREATE TABLE IF NOT EXISTS TAX_RATE (
    TAX_RATE_ID BIGINT NOT NULL AUTO_INCREMENT,
    TAX_TYPE VARCHAR(50) NOT NULL,        -- 부가세, 주세 등
    RATE DECIMAL(5,2) NOT NULL,           -- 세율 (%)
    EFFECTIVE_DATE DATE NOT NULL,         -- 적용 시작일
    PRIMARY KEY (TAX_RATE_ID)
);

-- 관리자 계정
CREATE TABLE IF NOT EXISTS ADMIN_CREDENTIALS (
    LOGIN_ID VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(200) NOT NULL
);