CREATE TABLE IF NOT EXISTS MENU (
    MENU_ID int NOT NULL AUTO_INCREMENT,
    MENU_NAME varchar(50) NOT NULL,
    MENU_TYPE varchar(20) NOT NULL,
    MENU_STATE varchar(50) NOT NULL,
    PRIMARY KEY (MENU_ID)
);

CREATE TABLE IF NOT EXISTS MENU_ITEM (
    MENU_ITEM_ID int NOT NULL AUTO_INCREMENT,
    MENU_ITEM_NAME varchar(50) NOT NULL,
    PRICE int NOT NULL,
    MENU_ITEM_STATE varchar(50) NOT NULL,
    MENU_ID bigint NOT NULL,
    PRIMARY KEY (MENU_ITEM_ID),
    FOREIGN KEY (MENU_ID) REFERENCES MENU(MENU_ID)
);

CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_NO char(24) NOT NULL,
    TOTAL_AMOUNT int NOT NULL,
    ORDER_STATE varchar(50) NOT NULL,
    ORDER_DATE datetime NOT NULL,
    WAITING_NO int,
    PRIMARY KEY (ORDER_NO)
);

CREATE TABLE IF NOT EXISTS ORDER_ITEM (
    ORDER_ITEM_ID bigint NOT NULL AUTO_INCREMENT,
    ORDER_ITEM_NAME varchar(50) NOT NULL,
    PRICE int NOT NULL,
    QUANTITY smallint NOT NULL,
    AMOUNT int NOT NULL,
    ORDER_NO char(24) NOT NULL,
    MENU_ITEM_ID bigint NOT NULL,
    PRIMARY KEY (ORDER_ITEM_ID),
    FOREIGN KEY (ORDER_NO) REFERENCES ORDERS(ORDER_NO),
    FOREIGN KEY (MENU_ITEM_ID) REFERENCES MENU_ITEM(MENU_ITEM_ID)
);

CREATE TABLE IF NOT EXISTS PAYMENT (
    PAYMENT_ID bigint NOT NULL AUTO_INCREMENT,
    PAYMENT_KEY varchar(50) NOT NULL,
    AMOUNT int NOT NULL,
    PAYMENT_STATE varchar(50) NOT NULL,
    ORDER_NO char(24) NOT NULL,
    PRIMARY KEY (PAYMENT_ID),
    FOREIGN KEY (ORDER_NO) REFERENCES ORDERS(ORDER_NO)
);

CREATE TABLE IF NOT EXISTS ADMIN_CREDENTIALS (
    LOGIN_ID varchar(50) NOT NULL,
    PASSWORD varchar(200) NOT NULL
);